package com.msfg.los.declarations.domain;

public enum Race {
    AMERICAN_INDIAN_OR_ALASKA_NATIVE,
    ASIAN,
    ASIAN_INDIAN,
    CHINESE,
    FILIPINO,
    JAPANESE,
    KOREAN,
    VIETNAMESE,
    OTHER_ASIAN,
    BLACK_OR_AFRICAN_AMERICAN,
    NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER,
    NATIVE_HAWAIIAN,
    GUAMANIAN_OR_CHAMORRO,
    SAMOAN,
    OTHER_PACIFIC_ISLANDER,
    WHITE,
    DO_NOT_WISH_TO_PROVIDE
}
