package com.msfg.los.origination.service;

import com.msfg.los.declarations.domain.BorrowerDeclarations;
import com.msfg.los.declarations.domain.BorrowerDemographics;
import com.msfg.los.declarations.service.DeclarationsService;
import com.msfg.los.declarations.service.DemographicsService;
import com.msfg.los.declarations.web.dto.DeclarationsRequest;
import com.msfg.los.declarations.web.dto.DemographicsRequest;
import com.msfg.los.financials.domain.Asset;
import com.msfg.los.financials.domain.Liability;
import com.msfg.los.financials.service.AssetService;
import com.msfg.los.financials.service.LiabilityService;
import com.msfg.los.financials.web.dto.AddAssetRequest;
import com.msfg.los.financials.web.dto.AddLiabilityRequest;
import com.msfg.los.income.domain.Employment;
import com.msfg.los.income.domain.IncomeItem;
import com.msfg.los.income.service.EmploymentService;
import com.msfg.los.income.service.IncomeService;
import com.msfg.los.income.web.dto.AddEmploymentRequest;
import com.msfg.los.income.web.dto.AddIncomeRequest;
import com.msfg.los.loan.domain.Loan;
import com.msfg.los.loan.domain.SubjectProperty;
import com.msfg.los.loan.service.LoanAccessGuard;
import com.msfg.los.loan.service.LoanService;
import com.msfg.los.loan.web.dto.CreateLoanRequest;
import com.msfg.los.loan.web.dto.UpdateLoanRequest;
import com.msfg.los.origination.web.dto.CloneResult;
import com.msfg.los.parties.domain.BorrowerParty;
import com.msfg.los.parties.service.BorrowerService;
import com.msfg.los.parties.web.dto.AddBorrowerRequest;
import com.msfg.los.reo.domain.RealEstateOwned;
import com.msfg.los.reo.service.ReoService;
import com.msfg.los.reo.web.dto.AddReoRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * "Copy to new" clone (Phase 2 T7): deep-copy a loan's applicant tree to a NEW loan.
 *
 * <p>The {@code origination} module is a leaf consumer — nothing depends on it, so there is no bean
 * cycle. Every read and write goes through an owning module's <strong>service</strong> (never another
 * module's repository), so validation, ordinals, and tenant-stamping all run, and the ArchUnit
 * {@code ModuleBoundaryTest} stays green. The whole operation is one {@code @Transactional} unit, so a
 * mid-failure rolls back and never leaves a half-cloned loan behind.
 *
 * <p><strong>Reset on clone</strong>:
 * <ul>
 *   <li>new {@code loanNumber} (auto-generated by {@code LoanService.create});</li>
 *   <li>{@code status} → STARTED (the create default) with a fresh {@code statusChangedAt};</li>
 *   <li>{@code loanOfficerId} = source's, or the caller when the source had none (LoanService.create
 *       defaults a null officer to the principal);</li>
 *   <li>borrower SSNs are DROPPED — stale NPI is re-collected (we never pass the source SSN);</li>
 *   <li>documents are NOT copied (they point at the source loan's storage);</li>
 *   <li>status timestamps / consummationDate start fresh (only §4 + property terms are carried).</li>
 * </ul>
 */
@Service
public class CloneService {

    private final LoanService loanService;
    private final LoanAccessGuard accessGuard;
    private final BorrowerService borrowerService;
    private final EmploymentService employmentService;
    private final IncomeService incomeService;
    private final AssetService assetService;
    private final LiabilityService liabilityService;
    private final ReoService reoService;
    private final DeclarationsService declarationsService;
    private final DemographicsService demographicsService;

    public CloneService(LoanService loanService,
                        LoanAccessGuard accessGuard,
                        BorrowerService borrowerService,
                        EmploymentService employmentService,
                        IncomeService incomeService,
                        AssetService assetService,
                        LiabilityService liabilityService,
                        ReoService reoService,
                        DeclarationsService declarationsService,
                        DemographicsService demographicsService) {
        this.loanService = loanService;
        this.accessGuard = accessGuard;
        this.borrowerService = borrowerService;
        this.employmentService = employmentService;
        this.incomeService = incomeService;
        this.assetService = assetService;
        this.liabilityService = liabilityService;
        this.reoService = reoService;
        this.declarationsService = declarationsService;
        this.demographicsService = demographicsService;
    }

    @Transactional
    public CloneResult clone(UUID sourceLoanId) {
        // Load the source (tenant-scoped: 404 cross-org / soft-deleted) + assert the caller may see it.
        Loan source = loanService.get(sourceLoanId);
        accessGuard.assertCanAccess(source);

        // 1) New loan: copy §4 + SubjectProperty, RESET number/status/timestamps. A null source
        //    officer makes LoanService.create default the caller (the principal) as LO.
        Loan target = createTargetLoan(source);
        UUID targetLoanId = target.getId();

        // 2) Borrowers — copy every field EXCEPT SSN (re-collect). Build source→new id map for the
        //    borrower-scoped trees and the REO owner remap.
        Map<UUID, UUID> borrowerIdMap = new HashMap<>();
        for (BorrowerParty src : borrowerService.listByLoan(sourceLoanId)) {
            BorrowerParty copy = borrowerService.add(targetLoanId, toAddBorrowerRequest(src));
            borrowerIdMap.put(src.getId(), copy.getId());
        }

        // 3) Per-borrower trees (employment + income, assets + liabilities, declarations + demographics).
        for (Map.Entry<UUID, UUID> e : borrowerIdMap.entrySet()) {
            UUID srcBorrowerId = e.getKey();
            UUID newBorrowerId = e.getValue();
            copyEmploymentAndIncome(sourceLoanId, srcBorrowerId, targetLoanId, newBorrowerId);
            copyAssets(sourceLoanId, srcBorrowerId, targetLoanId, newBorrowerId);
            copyLiabilities(sourceLoanId, srcBorrowerId, targetLoanId, newBorrowerId);
            copyDeclarationsAndDemographics(sourceLoanId, srcBorrowerId, targetLoanId, newBorrowerId);
        }

        // 4) REO (loan-scoped) — remap the owning borrower id onto its clone when present.
        copyReo(sourceLoanId, targetLoanId, borrowerIdMap);

        // Documents are intentionally NOT copied (they point at the source loan's storage).
        return new CloneResult(target.getId(), target.getLoanNumber());
    }

    /** Create the new loan, then carry §4 + SubjectProperty via the loan update path (validated). */
    private Loan createTargetLoan(Loan source) {
        CreateLoanRequest create = new CreateLoanRequest(
                source.getLoanPurpose(),
                source.getMortgageType(),
                source.getLienPriority(),
                source.getAmortizationType(),
                source.getNoteAmount(),
                source.getLoanOfficerId());   // null → LoanService.create defaults the caller as LO
        Loan target = loanService.create(create);

        SubjectProperty p = source.getSubjectProperty();
        UpdateLoanRequest update = new UpdateLoanRequest(
                source.getMortgageType(),
                source.getLienPriority(),
                source.getAmortizationType(),
                source.getNoteAmount(),
                p == null ? null : p.getAddressLine1(),
                p == null ? null : p.getAddressLine2(),
                p == null ? null : p.getCity(),
                p == null ? null : p.getState(),
                p == null ? null : p.getPostalCode(),
                p == null ? null : p.getEstimatedValue(),
                source.getDocumentationType(),
                source.getInterestRate(),
                source.getLoanTermMonths(),
                source.getBaseLoanAmount(),
                source.getFinancedFeesAmount(),
                source.getSecondLoanAmount(),
                source.getDownPaymentAmount(),
                source.getQualifyingCreditScore(),
                source.getProposedTaxesMonthly(),
                source.getProposedHazardInsuranceMonthly(),
                source.getProposedHoaDuesMonthly(),
                source.getProposedMortgageInsuranceMonthly(),
                p == null ? null : p.getSalesPrice(),
                p == null ? null : p.getAppraisedValue(),
                p == null ? null : p.getPropertyType(),
                p == null ? null : p.getOccupancyType(),
                p == null ? null : p.getNumberOfUnits(),
                null);   // consummationDate — fresh on the clone (TRID timing re-derived)
        loanService.update(target.getId(), update);
        return target;
    }

    /** Every borrower field EXCEPT ssn (left null — re-collect). primary preserved. */
    private AddBorrowerRequest toAddBorrowerRequest(BorrowerParty b) {
        return new AddBorrowerRequest(
                b.getFirstName(),
                b.getLastName(),
                b.isPrimary(),
                b.getMiddleName(),
                b.getSuffix(),
                null,                         // ssn DROPPED — stale NPI re-collected on the new loan
                b.getDateOfBirth(),
                b.getMaritalStatus(),
                b.getDependentsCount(),
                b.getDependentAges(),
                b.getCitizenshipType(),
                b.getVeteran(),
                b.getUnmarriedAddendumSpousalRights(),
                b.getJoinedToBorrowerId(),    // intra-loan link; rarely populated. Best-effort carry.
                b.getHomePhone(),
                b.getCellPhone(),
                b.getWorkPhone(),
                b.getWorkPhoneExt(),
                b.getEmail(),
                b.getNoEmail());
    }

    /**
     * Employment + income. Income items can reference an employment of the same borrower, so we map
     * each source employment id to its clone and re-point employment-typed income at the new id.
     */
    private void copyEmploymentAndIncome(UUID sourceLoanId, UUID srcBorrowerId,
                                         UUID targetLoanId, UUID newBorrowerId) {
        Map<UUID, UUID> employmentIdMap = new HashMap<>();
        for (Employment src : employmentService.list(sourceLoanId, srcBorrowerId)) {
            Employment copy = employmentService.add(targetLoanId, newBorrowerId, new AddEmploymentRequest(
                    src.getEmployerName(),
                    src.getEmployerPhone(),
                    src.getEmployerAddressLine1(),
                    src.getEmployerAddressLine2(),
                    src.getEmployerCity(),
                    src.getEmployerState(),
                    src.getEmployerPostalCode(),
                    src.getPositionTitle(),
                    src.getEmploymentStatus(),
                    src.getClassification(),
                    src.getSelfEmployed(),
                    src.getOwnershipShare(),
                    src.getEmployedByPartyToTransaction(),
                    src.getStartDate(),
                    src.getEndDate(),
                    src.getMonthsInLineOfWork()));
            employmentIdMap.put(src.getId(), copy.getId());
        }
        for (IncomeItem src : incomeService.list(sourceLoanId, srcBorrowerId)) {
            UUID newEmploymentId = src.getEmploymentId() == null
                    ? null
                    : employmentIdMap.get(src.getEmploymentId());
            incomeService.add(targetLoanId, newBorrowerId, new AddIncomeRequest(
                    src.getIncomeType(),
                    src.getMonthlyAmount(),
                    newEmploymentId,
                    src.getDescription()));
        }
    }

    private void copyAssets(UUID sourceLoanId, UUID srcBorrowerId, UUID targetLoanId, UUID newBorrowerId) {
        for (Asset src : assetService.list(sourceLoanId, srcBorrowerId)) {
            assetService.add(targetLoanId, newBorrowerId, new AddAssetRequest(
                    src.getAssetType(),
                    src.getFinancialInstitution(),
                    src.getAccountNumber(),
                    src.getCashOrMarketValue(),
                    src.getVerified()));
        }
    }

    private void copyLiabilities(UUID sourceLoanId, UUID srcBorrowerId, UUID targetLoanId, UUID newBorrowerId) {
        for (Liability src : liabilityService.list(sourceLoanId, srcBorrowerId)) {
            liabilityService.add(targetLoanId, newBorrowerId, new AddLiabilityRequest(
                    src.getLiabilityType(),
                    src.getCreditorName(),
                    src.getAccountNumber(),
                    src.getUnpaidBalance(),
                    src.getMonthlyPayment(),
                    src.isIncludeInDti(),
                    src.getExclusionReason(),
                    src.getMonthsRemaining()));
        }
    }

    /** Declarations + demographics are 1:1 per borrower (PUT-upsert); copy only when present. */
    private void copyDeclarationsAndDemographics(UUID sourceLoanId, UUID srcBorrowerId,
                                                 UUID targetLoanId, UUID newBorrowerId) {
        BorrowerDeclarations d = declarationsService.get(sourceLoanId, srcBorrowerId);
        if (d != null) {
            declarationsService.upsert(targetLoanId, newBorrowerId, new DeclarationsRequest(
                    d.getOccupyAsPrimaryResidence(),
                    d.getHadOwnershipInterestLast3Years(),
                    d.getFamilyOrBusinessAffiliationWithSeller(),
                    d.getBorrowingUndisclosedMoney(),
                    d.getApplyingForOtherMortgageOnProperty(),
                    d.getApplyingForNewCreditBeforeClosing(),
                    d.getSubjectToPriorityLienPace(),
                    d.getCoSignerOrGuarantorOnUndisclosedDebt(),
                    d.getOutstandingJudgments(),
                    d.getDelinquentOrDefaultOnFederalDebt(),
                    d.getPartyToLawsuit(),
                    d.getConveyedTitleInLieuLast7Years(),
                    d.getCompletedPreForeclosureShortSaleLast7Years(),
                    d.getPropertyForeclosedLast7Years(),
                    d.getDeclaredBankruptcyLast7Years(),
                    d.getPriorPropertyUsage(),
                    d.getPriorPropertyTitleType(),
                    d.getBankruptcyTypes()));
        }
        BorrowerDemographics dm = demographicsService.get(sourceLoanId, srcBorrowerId);
        if (dm != null) {
            demographicsService.upsert(targetLoanId, newBorrowerId, new DemographicsRequest(
                    dm.getEthnicity(),
                    dm.getRace(),
                    dm.getSex(),
                    dm.getCollectedByVisualObservationOrSurname(),
                    dm.getApplicationTakenMethod()));
        }
    }

    /** REO rows (loan-scoped). The owner borrower id is remapped onto the clone when it points at a copied borrower. */
    private void copyReo(UUID sourceLoanId, UUID targetLoanId, Map<UUID, UUID> borrowerIdMap) {
        List<RealEstateOwned> rows = reoService.list(sourceLoanId);
        for (RealEstateOwned src : rows) {
            UUID newOwner = src.getOwnerBorrowerId() == null
                    ? null
                    : borrowerIdMap.getOrDefault(src.getOwnerBorrowerId(), null);
            reoService.add(targetLoanId, new AddReoRequest(
                    newOwner,
                    src.isSubjectProperty(),
                    src.getAddressLine1(),
                    src.getAddressLine2(),
                    src.getCity(),
                    src.getState(),
                    src.getPostalCode(),
                    src.getPropertyType(),
                    src.getIntendedOccupancy(),
                    src.getPropertyStatus(),
                    src.getMarketValue(),
                    src.getGrossMonthlyRentalIncome(),
                    src.getMonthlyTaxes(),
                    src.getMonthlyInsurance(),
                    src.getMonthlyHoaDues(),
                    src.getMonthlyMaintenance(),
                    src.getMortgageUnpaidBalance(),
                    src.getMortgageMonthlyPayment()));
        }
    }
}
